Fix Mariadb testing
mysqljs/mysql pull request #2438
Opened 2020-11-30 19:57 UTC by rusher

MariaDB 5.5 and 10.0 version are EOL, Adding current GA version to test suite
change statistics test (mariadb doesn't have flush_tables)
change load data infile disable (MariaDB return a specific error 4166 : ER_LOAD_INFILE_CAPABILITY_DISABLED)

2020-12-01 01:15 UTC, dougwilson requested changes
Thank you!

2020-12-01 01:15 UTC, dougwilson commented on .travis.yml
> -      env: "DOCKER_MYSQL_TYPE=mariadb DOCKER_MYSQL_VERSION=5.5"
I understand these are EOL, but unless they are not working on Travis CI, we want to keep them here to ensure we do not break support until at least a major version bump of this module.

2020-12-01 01:15 UTC, dougwilson commented on test/integration/connection/test-statistics.js
> -    assert.ok(data.hasOwnProperty('flush_tables'));
This change affects even the MySQL tests.

2020-12-01 01:15 UTC, dougwilson commented on test/integration/connection/test-load-data-infile-disable.js
> +    // mariadb return 4166 error, mysql 1148
The assert should assert the correct one for each, not just let both codes for both different databases.

2020-12-01 10:40 UTC, rusher commented
Change as requested. 
I've added some utility functions to common in order to distinguish MariaDB from MySQL server and required minimum version.

2020-12-04 11:51 UTC, rusher commented
Closed, replaced by https://github.com/mysqljs/mysql/pull/2442, to have only one commit

2020-12-04 11:51 UTC, closed without merging